### PR TITLE
Only pin versions and direct dependencies in conda environment file

### LINKED ISSUE #1: Unable to create conda environment from YAML file
Thanks to @MauroCE for flagging this

On trying to create a conda environment from the provided [`environment.yml`](https://github.com/thiery-lab/manifold_lifting/blob/master/environment.yml) file by running

```
conda env create -f environment.yml
```

conda fails with error message

<details>
<summary>
<code>Solving environment: failed</code>
</summary>

```
ResolvePackageNotFound: 
  - scipy==1.8.0=py38h56a6a73_1
  - readline==8.1.2=h7f8727e_1
  - libllvm13==13.0.1=hf817b99_2
  - libwebp-base==1.2.2=h7f98852_1
  - libxkbcommon==1.0.3=he3ba5ed_0
  - libbrotlidec==1.0.9=h166bdaf_7
  - pthread-stubs==0.4=h36c2ea0_1001
  - icu==69.1=h9c3ff4c_0
  - hdf5==1.12.1=mpi_mpich_h5d83325_4
  - xorg-libxau==1.0.9=h7f98852_0
  - ca-certificates==2022.4.26=h06a4308_0
  - ncurses==6.3=h7f8727e_2
  - unicodedata2==14.0.0=py38h0a891b7_1
  - pyqtwebengine==5.12.1=py38h7400c14_8
  - krb5==1.19.3=h08a2579_0
  - importlib-metadata==4.11.3=py38h578d9bd_1
  - libev==4.33=h516909a_1
  - pkgconfig==1.5.5=py38h578d9bd_2
  - fonttools==4.33.3=py38h0a891b7_0
  - libsanitizer==10.3.0=h26c7422_16
  - grpc-cpp==1.45.2=h3ebbd8c_3
  - qt==5.12.9=h1304e3e_6
  - brotli-bin==1.0.9=h166bdaf_7
  - pyqt==5.12.3=py38h578d9bd_8
  - curl==7.83.1=h2283fc2_0
  - libxcb==1.13=h7f98852_1004
  - libglib==2.70.2=h174f98d_4
  - lz4-c==1.9.3=h9c3ff4c_1
  - petsc==3.16.6=real_h6e9d0b6_100
  - gmp==6.2.1=h58526e2_0
  - libgcc-ng==12.1.0=h8d9b700_16
  - libgfortran-ng==12.1.0=h69a702a_16
  - libevent==2.1.10=h28343ad_4
  - libuuid==2.32.1=h7f98852_1000
  - hdf4==4.2.15=h10796ff_3
  - pandas==1.4.2=py38h47df419_1
  - kiwisolver==1.4.2=py38h43d8883_1
  - freetype==2.10.4=h0708190_1
  - alsa-lib==1.2.3.2=h166bdaf_0
  - libtiff==4.3.0=h542a066_3
  - nss==3.77=h2350873_0
  - boost-cpp==1.74.0=h6cacc03_7
  - re2==2022.04.01=h27087fc_0
  - jbig==2.1=h7f98852_2003
  - sqlite==3.38.5=h4ff8645_0
  - libbrotlienc==1.0.9=h166bdaf_7
  - pillow==9.1.0=py38h0ee0e06_2
  - zlib==1.2.11=h166bdaf_1014
  - numpy==1.22.3=py38h99721a1_2
  - superlu==5.2.2=h16cfea0_0
  - c-ares==1.18.1=h7f98852_0
  - cmake==3.23.1=h5432695_0
  - mpfr==4.1.0=h9202a9a_1
  - pyqtchart==5.12=py38h7400c14_8
  - abseil-cpp==20211102.0=h27087fc_1
  - _openmp_mutex==4.5=2_gnu
  - gmpy2==2.1.2=py38h8384b0a_0
  - hypre==2.24.0=mpi_mpich_h0faba72_0
  - libiconv==1.16=h516909a_0
  - gettext==0.19.8.1=h73d1719_1008
  - lcms2==2.12=hddcbb42_0
  - gst-plugins-base==1.20.2=hcf0ee16_0
  - matplotlib==3.5.2=py38h578d9bd_0
  - libwebp==1.2.2=h3452ae3_0
  - mpich==4.0.2=h846660c_100
  - fenics-libdolfin==2019.1.0=h5416c5e_29
  - bzip2==1.0.8=h7f98852_4
  - libpng==1.6.37=h21135ba_2
  - scikit-sparse==0.4.6=py38h60dfaa3_1
  - suitesparse==5.10.1=h9e50725_1
  - matplotlib-base==3.5.2=py38h826bfd8_0
  - mpi4py==3.1.3=py38h97ac3a3_1
  - slepc==3.16.1=real_h7bbb3bb_101
  - petsc4py==3.16.6=real_hc9bd64a_100
  - pybind11==2.9.2=py38h43d8883_1
  - mpc==1.2.1=h9f54685_0
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - fftw==3.3.10=mpi_mpich_h8b92f0a_2
  - libopus==1.3.1=h7f98852_1
  - libssh2==1.10.0=ha35d2d1_2
  - libzlib==1.2.11=h166bdaf_1014
  - libcurl==7.83.1=h2283fc2_0
  - libedit==3.1.20191231=he28a2e2_2
  - libogg==1.3.4=h7f98852_1
  - ptscotch==6.0.9=hb499603_2
  - jaxlib==0.3.7=py38h5a7fad5_0
  - lerc==3.0=h9c3ff4c_0
  - libclang==13.0.1=default_hc23dcda_0
  - libxml2==2.9.12=h885dcf4_1
  - mysql-common==8.0.29=h26416b9_0
  - keyutils==1.6.1=h166bdaf_0
  - libffi==3.4.2=h7f98852_5
  - scalapack==2.2.0=hd931219_1
  - tk==8.6.12=h27826a3_0
  - libvorbis==1.3.7=h9c3ff4c_0
  - rhash==1.4.1=h7f98852_0
  - libprotobuf==3.20.1=h6239696_0
  - libstdcxx-ng==12.1.0=ha89aaad_16
  - libnetcdf==4.8.1=mpi_mpich_hcdf9059_2
  - yaml==0.2.5=h7f98852_2
  - pyqt5-sip==4.19.18=py38h709712a_8
  - eigen==3.4.0=h4bd325d_0
  - jpeg==9e=h166bdaf_1
  - netcdf4==1.5.8=nompi_py38h2823cc8_101
  - tornado==6.1=py38h0a891b7_3
  - libzip==1.8.0=h1c5bbd1_1
  - libgfortran5==12.1.0=hdcd56e2_16
  - multiprocess==0.70.12.2=py38h0a891b7_2
  - mysql-libs==8.0.29=hbc51c84_0
  - fenics-ffc==2019.1.0=py38h578d9bd_29
  - scotch==6.0.9=hb2e6521_2
  - expat==2.4.8=h27087fc_0
  - pkg-config==0.29.2=h36c2ea0_1008
  - superlu_dist==7.2.0=h25dcc4a_0
  - fenics-ufl==2019.1.0=py38h578d9bd_29
  - fontconfig==2.14.0=h8e229c2_0
  - pybind11-global==2.9.2=py38h43d8883_1
  - xz==5.2.5=h7f8727e_1
  - openssl==3.0.3=h166bdaf_0
  - setuptools==61.2.0=py38h06a4308_0
  - cftime==1.6.0=py38h71d37f0_1
  - pip==21.2.4=py38h06a4308_0
  - gstreamer==1.20.2=hd4edc92_0
  - fenics-dolfin==2019.1.0=py38hdaacf68_29
  - libopenblas==0.3.20=pthreads_h78a6416_0
  - python==3.8.13=ha86cf86_0_cpython
  - tbb==2021.5.0=h924138e_1
  - sympy==1.10.1=py38h578d9bd_0
  - pcre==8.45=h9c3ff4c_0
  - libdeflate==1.10=h7f98852_0
  - dbus==1.13.6=h5008d03_3
  - certifi==2021.10.8=py38h578d9bd_2
  - _libgcc_mutex==0.1=conda_forge
  - fenics-fiat==2019.1.0=py38h578d9bd_29
  - fenics-dijitso==2019.1.0=py38h578d9bd_29
  - libbrotlicommon==1.0.9=h166bdaf_7
  - pyqt-impl==5.12.3=py38h0ffb2e6_8
  - mumps-mpi==5.2.1=h7ee95aa_11
  - libuv==1.43.0=h7f98852_0
  - slepc4py==3.16.1=real_h34bd6fb_100
  - libnghttp2==1.47.0=he49606f_0
  - parmetis==4.0.3=h2a9763c_1005
  - nspr==4.32=h9c3ff4c_1
  - zstd==1.5.2=ha95c52a_0
  - metis==5.1.0=h58526e2_1006
  - libgomp==12.1.0=h8d9b700_16
  - giflib==5.2.1=h36c2ea0_2
  - openjpeg==2.4.0=hb52868f_1
  - libnsl==2.0.0=h7f98852_0
  - mumps-include==5.2.1=ha770c72_11
  - brotli==1.0.9=h166bdaf_7
  - libpq==14.3=he2d8382_0
```
</details>

It could be this is due to the environment YAML file pinning the builds of the packages rather than just their versions leading to problems resolving the dependencies when trying to create the environment on a different system from used to create the original environment file. It might also be better to have environment file which only specifies the direct rather than direct plus transitive dependencies.

### PR DESCRIPTION
**Pull request by matt-graham**
(Hopefully) fixes #1 

Specifies only direct dependencies in `environment.yml` file and pins only the package versions not their builds.

Also added a line to install `mlift` package from tag on GitHub to avoid having to do as a separate step.

### CODE REVIEW

**Comment by matt-graham** [comment]
@MauroCE if you get a chance could you check if creating an environment from the updated YAML file on this branch fixes your issue! Thanks 😄

**Comment by MauroCE** [comment]
Thanks! I replaced the `environment.yml` file with the new version and now I get this error:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - fenics-dolfin=2019.1.0
  - scikit-sparse=0.4.6
```

**Comment by matt-graham** [comment]
@MauroCE thanks for trying this out. Can I check what operating system you are using? It looks like both `fenics-dolfin` and `scikit-sparse` don't have `win64` builds available so if you are on Windows that might explain things. If so using [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install) is probably the easiest way to get things working (I tested building the environment from the YAML file on WSL on my Windows work computer and it worked without any problems). If this does solve the problem I'll update the instructions in the README to say to use WSL if on Windows.

**Comment by matt-graham** [comment]
Also `fenics-dolfin` and `scikit-sparse` are only actually required for running the Poisson partial differential equation model numerical experiments. If you don't need to run this specific set of experiments, an alternative which wouldn't require installing WSL would be to just create an environment with the remaining dependencies by running
```
conda create -n man-lift -y
conda activate man-lift
conda install -y -c conda-forge python=3.9 pip=22.2 numpy=1.23.1 scipy=1.8.1 arviz=0.12.1 jax=0.3.15 sympy=1.10.1 multiprocess=0.70.13 matplotlib=3.5.2
pip install mici==0.1.10 symnum==0.1.2 git+https://github.com/thiery-lab/manifold_lifting@v0.1.0#egg=mlift
```
To run the simulated data experiments for all models other than the Poisson model you would then run
```
MODELS="fitzhugh_nagumo nonlinear_ssm hh_current_stimulus" bash run_simulated_data_experiments.sh
```

**Comment by MauroCE** [comment]
> @MauroCE thanks for trying this out. Can I check what operating system you are using? It looks like both `fenics-dolfin` and `scikit-sparse` don't have `win64` builds available so if you are on Windows that might explain things. If so using [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install) is probably the easiest way to get things working (I tested building the environment from the YAML file on WSL on my Windows work computer and it worked without any problems). If this does solve the problem I'll update the instructions in the README to say to use WSL if on Windows.

Hi Matt, I am using MacOS Monterey on a M1 mac so perhaps that could be creating issues. I have tried the solution you've suggested in the latest comment and it worked! Thank you so much for the help :)

**Comment by matt-graham** [comment]
Thanks @MauroCE - that makes sense wrt you being on a M1 Mac as the `fenics-dolfin` and `scikit-sparse` packages also don't have `osx-arm64` builds available. I'll add a note to the README similar to my comment above to explain how to set up an environment without those dependencies for those using Windows or a M1 Mac.

**Pull request merged**
